#!/usr/bin/python
from __future__ import print_function
import requests
import sys
import os


def weather_str(weather_info):
    obs = weather_info['current_observation']
    ret_str = '{0} - {1}, {2}F ({3}C), Wind {4} @ {5}~{6}mph, Humidity {7} (Weather Underground)'.format(
                  obs['observation_location']['full'],
                  obs['weather'],
                  obs['temp_f'], obs['temp_c'],
                  obs['wind_dir'], obs['wind_mph'], obs['wind_gust_mph'],
                  obs['relative_humidity'])
    return ret_str


def weather_get(key, zc):
    ret = requests.get('http://api.wunderground.com/api/' + key + '/geolookup/conditions/q/' + zc + '.json')
    if ret.status_code == 200:
        return weather_str(ret.json())
    return 'Failed to obtain weather (' + str(ret.status_code) + ')'


def main():
    key = os.getenv('WUNDERGROUND_KEY')
    if key == '':
        print('WUNDERGROUND_KEY is not in environment')
    args = sys.argv
    if len(args) < 2:
        print('Need a zip code')
        return 1
    print(weather_get(key, args[1]))


if __name__ == '__main__':
    exit(main())
