#!/usr/bin/python
from __future__ import print_function
import requests
import sys
import os


def weather_str(weather_info):
    try:
        obs = weather_info['current_observation']
        ret_str = '{0}, {1}F ({2}C), Wind {3} @ {4}~{5}mph, Humidity {6} (Weather Underground)'.format(
                      obs['weather'],
                      obs['temp_f'], obs['temp_c'],
                      obs['wind_dir'], obs['wind_mph'], obs['wind_gust_mph'],
                      obs['relative_humidity'])
    except KeyError:
        ret_str = 'No weather data available; try again later.'
    return ret_str


def weather_get(key, zc):
    ret = requests.get('http://api.wunderground.com/api/' + key + '/geolookup/conditions/q/' + zc + '.json')
    if ret.status_code == 200:
        return weather_str(ret.json())
    return 'Failed to obtain weather (' + str(ret.status_code) + ')'


def main():
    key = os.getenv('WUNDERGROUND_KEY')
    if key == '':
        print('WUNDERGROUND_KEY is not in environment')
        return 1
    args = sys.argv
    if len(args) < 2:
        print('Need a zip code')
        return 1
    print(weather_get(key, args[1]))
    return 0


if __name__ == '__main__':
    exit(main())
